; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[adminrole][subdir] = "contrib"
projects[adminrole][version] = "1.1"

projects[auto_nodetitle][version] = "1.0"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "2.3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.17"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[draggableviews][version] = "2.1"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.14"

projects[entity][version] = "1.6"

projects[features][version] = "2.10"

projects[media][version] = "1.5"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.2"

projects[jcarousel][version] = "2.7"

projects[lightbox2][version] = "1.0-beta1"

projects[link][version] = "1.3"

projects[master][subdir] = "contrib"
projects[master][version] = "2.0-beta4"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.14"

projects[mobile_theme][version] = "1.2"

projects[panels][version] = "3.5"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.3"

projects[rotating_banner][version] = "2.x-dev"

projects[stage_file_proxy][subdir] = "contrib"
projects[stage_file_proxy][version] = "1.7"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[subpathauto][subdir] = "contrib"
projects[subpathauto][version] = "1.3"

projects[token][version] = "1.6"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta11"

projects[views][version] = "3.11"

projects[wysiwyg][version] = "2.2"

; Themes
projects[mobile][version] = "2.0"


