; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[adminrole][subdir] = "contrib"
projects[adminrole][version] = "1.1"

projects[auto_nodetitle][version] = "1.0"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "2.3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

; projects[ckeditor][subdir] = "contrib"
; projects[ckeditor][version] = "1.17"

projects[ckeditor_media][subdir] = "contrib"
projects[ckeditor_media][version] = "2.0-beta2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.10-rc1"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[draggableviews][version] = "2.1"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.7"

projects[features][subdir] = "contrib"
projects[features][version] = "2.10"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-beta2"

projects[fontyourface][subdir] = "contrib"
projects[fontyourface][version] = "2.8"
projects[fontyourface][patches][0] = "./patches/fontyourface-wysiwyg.patch"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.2"

projects[panels][version] = "3.5"

projects[imagecache_token][subdir] = "contrib"
projects[imagecache_token][version] = "1.0-rc2"

projects[jcarousel][version] = "2.7"

projects[lightbox2][subdir] = "contrib"
projects[lightbox2][version] = "2.0"

projects[link][subdir] = "contrib"
projects[link][version] = "1.4"

projects[master][subdir] = "contrib"
projects[master][version] = "2.0-beta4"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-beta1"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.14"

projects[node_clone][subdir] = "contrib"
projects[node_clone][version] = "1.0"

projects[noindex_external_links][subdir] = "contrib"
projects[noindex_external_links][version] = "2.0-rc1"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.3"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc3"

projects[rotating_banner][version] = "2.x-dev"

projects[stage_file_proxy][subdir] = "contrib"
projects[stage_file_proxy][version] = "1.7"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[subpathauto][subdir] = "contrib"
projects[subpathauto][version] = "1.3"

projects[token][version] = "1.6"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[twitter][subdir] = "contrib"
projects[twitter][version] = "5.11"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta11"

projects[views][subdir] = "contrib"
projects[views][version] = "3.13"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.x-dev"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.3"

; Themes
projects[mobile][version] = "2.0"


; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.5.9/ckeditor_4.5.9_full.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

