<?php

$conf['install_profile'] = 'minimal';
$conf['master_version'] = 2;
$conf['master_modules'] = array(
  'base' => array(
    'minimal',
    'admin_menu_toolbar',
    'adminrole',
    'auto_nodetitle',
    'block_class',
    'blog',
    'ckeditor_media',
    'clone',
    'contact',
    'contextual',
    'date',
    'draggableviews',
    'features',
    'fontyourface_ui',
    'fontyourface_wysiwyg',
    'globalredirect',
    'googleanalytics',
    'imagecache_token',
    'jcarousel',
    'lightbox2',
    'link',
    'media_internet',
    'menu',
    'metatag',
    'metatag_dc',
    'metatag_facebook',
    'metatag_google_plus',
    'metatag_opengraph',
    'metatag_twitter_cards',
    'page_manager',
    'panels_node',
    'pathauto',
    'php',
    'rdf',
//     'remove_ron',
    'rotating_banner',
    'strongarm',
    'subpathauto',
    'statistics',
    'taxonomy',
    'tracker',
    'transliteration',
    'typekit_api',
    'update',
    'video_embed_field',
    'wysiwyg',
    'xmlsitemap',
    'xmlsitemap_engines',
    'xmlsitemap_menu',
    'xmlsitemap_node',
/*
    'adsense',
    'adsense_managed',
    'auto_nodetitle',
    'backup_migrate',
    'better_formats',
    'bootstrap',
    'codefilter',
    'ds',
    'ds_extras',
    'ds_format',
    'entity_token',
    'entityreference',
    'exif_custom',
    'feeds',
    'feeds_tamper',
    'field_group',
    'geshifield',
    'htmlpurifier',
    'job_scheduler',
    'list',
    'logintoboggan',
    'markdown',
    'media_bulk_upload',
    'media_migrate_file_types',
    'media_wysiwyg_view_mode',
    'multiform',
    'nice_menus',
    'noindex_external_links',
    'number',
    'plupload',
    'publication_date',
    'redirect',
    'swiftype_integration',
    'taxonomy_menu',
    'twitter_actions',
    'twitter_post',
    'typogrify',


// GDG modules
    'basic_config',
    'content_dashboard',
    'earthquake_news',
    'feeds_article',
    'section_taxonomy',
*/
  ),

  'local' => array(
    'dblog',
    'devel',
    'diff',
//     'ds_devel',
//     'ds_ui',
//     'feeds_tamper_ui',
//     'feeds_ui',
    'field_ui',
    'stage_file_proxy',
    'views_ui',
  ),

  'dev' => array(
    'dblog',
    'devel',
    'diff',
//     'ds_devel',
//     'ds_ui',
//     'feeds_tamper_ui',
//     'feeds_ui',
    'field_ui',
    'stage_file_proxy',
    'views_ui',
  ),

  'prod' => array(),

);
$conf['master_uninstall_blacklist'] = array(
  'base' => array(
//     0 => 'ckeditor',
  ),
);
$conf['master_removable_blacklist'] = array(
  0 => 'modules/*',
);
